
export const STATIC_PROPERTIES = [
    // OFF-PLAN / FIRST LAUNCHES (6 Items)
    {
        id: 'op1-static',
        title: 'Seaside Ritual',
        type: 'Apartment',
        location: 'Rashid Yachts & Marina',
        price: 1900000,
        bedrooms: 2,
        bathrooms: 2,
        area_sqft: 1250,
        parking: 1,
        status: 'Reserved',
        featured: 1,
        category: 'off_plan',
        image: 'https://images.unsplash.com/photo-1512914890251-2f96a9b0bbe2?q=80&w=600&auto=format&fit=crop',
        description: 'A premier waterfront destination offering a seamless blend of marina lifestyle.'
    },
    {
        id: 'op2-static',
        title: 'The Heights Country Club',
        type: 'Villa',
        location: 'Al Yalayis',
        price: 3400000,
        bedrooms: 4,
        bathrooms: 4,
        area_sqft: 3500,
        parking: 2,
        status: 'Reserved',
        featured: 1,
        category: 'off_plan',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=600&auto=format&fit=crop',
        description: 'An exclusive retreat focused on wellness and leisure.'
    },
    {
        id: 'op3-static',
        title: 'Zenith Skylofts',
        type: 'Penthouse',
        location: 'Business Bay',
        price: 2800000,
        bedrooms: 3,
        bathrooms: 3,
        area_sqft: 2800,
        parking: 2,
        status: 'Reserved',
        featured: 1,
        category: 'off_plan',
        image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=600&auto=format&fit=crop',
        description: 'Redefining vertical living in the business capital.'
    },
    {
        id: 'op4-static',
        title: 'Oasis Terraces',
        type: 'Apartment',
        location: 'Meydan',
        price: 2100000,
        bedrooms: 2,
        bathrooms: 2,
        area_sqft: 1400,
        parking: 1,
        status: 'Reserved',
        featured: 1,
        category: 'off_plan',
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=600&auto=format&fit=crop',
        description: 'A sanctuary of tranquility, combining modern architecture with luscious greenery.'
    },
    {
        id: 'op5-static',
        title: 'Palace Residences',
        type: 'Apartment',
        location: 'Dubai Creek Harbour',
        price: 1600000,
        bedrooms: 1,
        bathrooms: 1,
        area_sqft: 950,
        parking: 1,
        status: 'Reserved',
        featured: 1,
        category: 'off_plan',
        image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=600&auto=format&fit=crop',
        description: 'Bring the grandeur of the Palace hotel brand to your private residence.'
    },
    {
        id: 'op6-static',
        title: 'Velvet Residences',
        type: 'Apartment',
        location: 'Safe Park',
        price: 2500000,
        bedrooms: 2,
        bathrooms: 2,
        area_sqft: 1350,
        parking: 1,
        status: 'Reserved',
        featured: 1,
        category: 'off_plan',
        image: 'https://images.unsplash.com/photo-1600607687940-c52af084399c?q=80&w=600&auto=format&fit=crop',
        description: 'Sophisticated urban living designed for the modern connoisseur.'
    },

    // READY ASSETS (APARTMENTS - 4 Items)
    {
        id: 'r1-static-new',
        title: 'Opera District Residences',
        type: 'Apartment',
        location: 'Downtown Dubai',
        price: 4800000,
        bedrooms: 2,
        bathrooms: 2,
        area_sqft: 1450,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'ready',
        image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=600&auto=format&fit=crop',
        description: 'Ultra-modern living in the cultural heart of Downtown.',
        listing_type: 'Sale'
    },
    {
        id: 'r2-static-new',
        title: 'Marina Gate Exclusive',
        type: 'Apartment',
        location: 'Dubai Marina',
        price: 3950000,
        bedrooms: 2,
        bathrooms: 2,
        area_sqft: 1350,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'ready',
        image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?q=80&w=600&auto=format&fit=crop',
        description: 'Located at the gateway to the Marina, combining luxury with convenience.',
        listing_type: 'Sale'
    },
    {
        id: 'r3-static-new',
        title: 'Canal Front Residences',
        type: 'Apartment',
        location: 'Business Bay',
        price: 2200000,
        bedrooms: 1,
        bathrooms: 1,
        area_sqft: 950,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'ready',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=600&auto=format&fit=crop',
        description: 'The perfect investment for professionals in a prime location.',
        listing_type: 'Sale'
    },
    {
        id: 'r4-static-new',
        title: 'Marina Bliss Suite',
        type: 'Apartment',
        location: 'Dubai Marina',
        price: 120000,
        bedrooms: 1,
        bathrooms: 1,
        area_sqft: 850,
        parking: 1,
        status: 'active',
        featured: 0,
        category: 'ready',
        image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=600&auto=format&fit=crop',
        description: 'Beautiful marina views available for rent.',
        listing_type: 'Rent',
        rent_frequency: 'Yearly'
    },

    // READY ASSETS (TOWNHOUSES & VILLAS)
    {
        id: 'th1-static',
        title: 'Maple Family Estate',
        type: 'Townhouse',
        location: 'Dubai Hills',
        price: 4500000,
        bedrooms: 4,
        bathrooms: 4,
        area_sqft: 3200,
        parking: 2,
        status: 'active',
        featured: 0,
        category: 'ready',
        image: 'https://images.unsplash.com/photo-1600566753190-17f0bb2a6c3e?q=80&w=600&auto=format&fit=crop',
        description: 'Spacious family living in the most desirable green community.'
    },
    {
        id: 'th2-static',
        title: 'Emerald Hills Townhouse',
        type: 'Townhouse',
        location: 'Dubai Hills',
        price: 6200000,
        bedrooms: 5,
        bathrooms: 5,
        area_sqft: 4100,
        parking: 2,
        status: 'active',
        featured: 0,
        category: 'ready',
        image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=600&auto=format&fit=crop',
        description: 'A premium, corner-unit townhouse with architectural finishes.'
    },
    {
        id: 'th3-static',
        title: 'Jumeirah Islands Garden',
        type: 'Townhouse',
        location: 'Jumeirah Islands',
        price: 5900000,
        bedrooms: 4,
        bathrooms: 4,
        area_sqft: 3800,
        parking: 2,
        status: 'active',
        featured: 0,
        category: 'ready',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=600&auto=format&fit=crop',
        description: 'A serene sanctuary offering complete privacy and luxury.'
    },
    {
        id: 'v2-static',
        title: 'The Royal Frond Palace',
        type: 'Villa',
        location: 'Palm Jumeirah',
        price: 85000000,
        bedrooms: 7,
        bathrooms: 8,
        area_sqft: 11200,
        parking: 6,
        status: 'active',
        featured: 1,
        category: 'ready',
        image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=600&auto=format&fit=crop',
        description: 'A titan of architectural prowess on Palm Jumeirah.'
    },

    // PRIME CITY
    {
        id: 'p1-static-prime',
        title: 'Burj Vista Sky Collection',
        type: 'Penthouse',
        location: 'Downtown Dubai',
        price: 15500000,
        bedrooms: 4,
        bathrooms: 5,
        area_sqft: 4200,
        parking: 2,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1600607687940-c52af084399c?q=80&w=600&auto=format&fit=crop',
        description: 'A masterpiece of architecture and design.'
    },
    {
        id: 'p2-static-prime',
        title: 'Frond M Signature Villa',
        type: 'Villa',
        location: 'Palm Jumeirah',
        price: 62000000,
        bedrooms: 6,
        bathrooms: 7,
        area_sqft: 8500,
        parking: 4,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=600&auto=format&fit=crop',
        description: 'Exclusive beachside living on the world-famous Palm Jumeirah.'
    },

    // DUBAI MARINA PRIME COLLECTION (Matching Frontend Auto-Fill)
    {
        id: 'dm-prime-1',
        title: 'Marina Gate Exclusive (Prime)',
        type: 'Apartment',
        location: 'Dubai Marina',
        price: 3950000,
        bedrooms: 2,
        bathrooms: 2,
        area_sqft: 1350,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?q=80&w=600&auto=format&fit=crop',
        description: 'Prime waterfront living.'
    },
    {
        id: 'dm-prime-2',
        title: 'Marina Gate Exclusive 2',
        type: 'Apartment',
        location: 'Dubai Marina',
        price: 3950000,
        bedrooms: 2,
        bathrooms: 2,
        area_sqft: 1350,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?q=80&w=600&auto=format&fit=crop',
        description: 'Prime waterfront living.'
    },
    {
        id: 'dm-prime-3',
        title: 'Marina Gate Exclusive 3',
        type: 'Apartment',
        location: 'Dubai Marina',
        price: 3950000,
        bedrooms: 2,
        bathrooms: 2,
        area_sqft: 1350,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?q=80&w=600&auto=format&fit=crop',
        description: 'Prime waterfront living.'
    },
    {
        id: 'dm-prime-4',
        title: 'Marina Gate Exclusive 4',
        type: 'Apartment',
        location: 'Dubai Marina',
        price: 3950000,
        bedrooms: 2,
        bathrooms: 2,
        area_sqft: 1350,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?q=80&w=600&auto=format&fit=crop',
        description: 'Prime waterfront living.'
    },

    // BUSINESS BAY PRIME COLLECTION
    {
        id: 'bb-prime-1',
        title: 'Canal Front Residences (Prime)',
        type: 'Apartment',
        location: 'Business Bay',
        price: 2200000,
        bedrooms: 1,
        bathrooms: 1,
        area_sqft: 950,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=600&auto=format&fit=crop',
        description: 'The perfect investment for professionals.'
    },
    {
        id: 'bb-prime-2',
        title: 'Canal Front Residences 2',
        type: 'Apartment',
        location: 'Business Bay',
        price: 2200000,
        bedrooms: 1,
        bathrooms: 1,
        area_sqft: 950,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=600&auto=format&fit=crop',
        description: 'The perfect investment for professionals.'
    },
    {
        id: 'bb-prime-3',
        title: 'Canal Front Residences 3',
        type: 'Apartment',
        location: 'Business Bay',
        price: 2200000,
        bedrooms: 1,
        bathrooms: 1,
        area_sqft: 950,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=600&auto=format&fit=crop',
        description: 'The perfect investment for professionals.'
    },
    {
        id: 'bb-prime-4',
        title: 'Canal Front Residences 4',
        type: 'Apartment',
        location: 'Business Bay',
        price: 2200000,
        bedrooms: 1,
        bathrooms: 1,
        area_sqft: 950,
        parking: 1,
        status: 'active',
        featured: 1,
        category: 'prime',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=600&auto=format&fit=crop',
        description: 'The perfect investment for professionals.'
    }
];
